#!/usr/bin/env bash
# install-mac.sh - put every tool in this repo on PATH under zsh on macOS.
#
#   ./install-mac.sh            # install / re-sync (safe to re-run)
#   ./install-mac.sh --rc FILE  # write the PATH block to FILE instead of ~/.zshrc
#   ./uninstall-mac.sh          # undo it
#
# install.sh is the Linux counterpart. macOS needs a separate script for two
# reasons: the rc file is always ~/.zshrc, and Homebrew's python is PEP 668
# "externally managed" - it refuses `pip install --user`, so dependencies have
# to go in a repo-local .venv/ and the entry points have to be pointed at it.
#
# Written for bash 3.2 (what macOS still ships) - no readlink -f, no sed -i.

set -eu

BEGIN_MARK='# >>> tools (managed by install-mac.sh) >>>'
END_MARK='# <<< tools (managed by install-mac.sh) <<<'

ROOT=$(cd "$(dirname "$0")" && pwd)
VENV="$ROOT/.venv"
RC=""

while [ $# -gt 0 ]; do
    case "$1" in
        --rc)      RC="${2:-}"; shift 2 ;;
        -h|--help) sed -n '2,14p' "$0" | cut -c3-; exit 0 ;;
        *)         echo "install-mac.sh: unknown option $1" >&2; exit 2 ;;
    esac
done
[ -n "$RC" ] || RC="$HOME/.zshrc"

[ "$(uname -s)" = "Darwin" ] || echo "install-mac.sh: not macOS - you probably want ./install.sh" >&2

# --------------------------------------------------------------------------
# Python: always a repo-local venv
#
# Unconditional rather than "only if the system python is short a package".
# On macOS the system python is either Apple's (no pip at all) or Homebrew's
# (PEP 668), so the venv is needed in practice every time, and always taking
# the same path keeps what lands in bin/ predictable. Nothing outside the repo
# is touched.
# --------------------------------------------------------------------------
command -v python3 >/dev/null 2>&1 || {
    echo "install-mac.sh: python3 not found - brew install python" >&2
    exit 1
}

[ -x "$VENV/bin/python3" ] || python3 -m venv "$VENV" || {
    echo "install-mac.sh: could not create a venv at $VENV" >&2
    exit 1
}

missing=""
for req in "$ROOT"/*/requirements.txt; do
    [ -f "$req" ] || continue
    "$VENV/bin/python3" -m pip install --quiet --disable-pip-version-check \
        --upgrade-strategy only-if-needed -r "$req" || true
    # Verify rather than trust pip's exit status, so an offline install still
    # reports precisely what is unusable. Module name is guessed from the
    # distribution name (strip version specifier, '-' -> '_'), which holds for
    # the small deps these tools use.
    while read -r pkg; do
        case "$pkg" in ''|'#'*) continue ;; esac
        mod=$(echo "$pkg" | sed 's/[<>=!].*//' | tr '-' '_')
        "$VENV/bin/python3" -c "import $mod" >/dev/null 2>&1 || missing="$missing $pkg"
    done < "$req"
done

# --------------------------------------------------------------------------
# Entry points:  <tool>/bin/*  ->  bin/*
#
# Python entry points get a generated wrapper, not a symlink: their
# `#!/usr/bin/env python3` shebang would otherwise pick the Homebrew
# interpreter, which is the one missing the deps. Anything else is a relative
# symlink and runs under its own shebang.
# --------------------------------------------------------------------------
rm -rf "$ROOT/bin"
mkdir -p "$ROOT/bin"

linked=""
for exe in "$ROOT"/*/bin/*; do
    [ -f "$exe" ] || continue
    [ -x "$exe" ] || chmod +x "$exe"
    name=$(basename "$exe")
    if [ -e "$ROOT/bin/$name" ]; then
        echo "install-mac.sh: two tools both provide '$name', skipping $exe" >&2
        continue
    fi
    tool=$(basename "$(dirname "$(dirname "$exe")")")
    case "$(head -n 1 "$exe")" in
        *python*)
            # No absolute paths in the wrapper: it finds the repo by walking up
            # from itself, so tools/ can be moved or cloned anywhere and this
            # keeps working without a re-install. The readlink loop lets the
            # wrapper also be symlinked onto PATH from somewhere else
            # (~/.local/bin/gsv -> .../tools/bin/gsv); a plain `dirname $0`
            # would resolve to the symlink's directory, not the repo's.
            {
                echo '#!/bin/sh'
                echo "# generated by install-mac.sh - runs $tool under the repo venv"
                echo 'self=$0'
                echo 'while [ -L "$self" ]; do'
                echo '    link=$(readlink "$self")'
                echo '    case "$link" in'
                echo '        /*) self=$link ;;'
                echo '        *)  self=$(dirname "$self")/$link ;;'
                echo '    esac'
                echo 'done'
                echo 'root=$(cd "$(dirname "$self")/.." && pwd)'
                echo 'py="$root/.venv/bin/python3"'
                echo 'if [ ! -x "$py" ]; then'
                echo "    echo \"$name: \$root/.venv is missing or broken - re-run \$root/install-mac.sh\" >&2"
                echo '    py=python3'
                echo 'fi'
                echo "exec \"\$py\" \"\$root/$tool/bin/$name\" \"\$@\""
            } > "$ROOT/bin/$name"
            chmod +x "$ROOT/bin/$name"
            ;;
        *)
            ln -s "../$tool/bin/$name" "$ROOT/bin/$name"
            ;;
    esac
    linked="$linked $name"
done
[ -n "$linked" ] || { echo "install-mac.sh: found no */bin/* entry points in $ROOT" >&2; exit 1; }

# --------------------------------------------------------------------------
# PATH block
#
# The one place an absolute path is unavoidable - an rc file has to name the
# repo somehow. Everything it points at is self-locating, so after moving the
# repo the only thing to redo is ./install-mac.sh. The -d guard keeps a stale
# block inert instead of putting a dead directory on PATH.
# --------------------------------------------------------------------------
strip_block() {
    [ -f "$RC" ] || return 0
    awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
        $0 == b { skip = 1 }
        skip != 1 { print }
        $0 == e { skip = 0 }
    ' "$RC" > "$RC.tools.tmp"
    mv "$RC.tools.tmp" "$RC"
}

strip_block
[ -f "$RC" ] || : > "$RC"
{
    echo ""
    echo "$BEGIN_MARK"
    echo "export TOOLS_HOME=\"$ROOT\""
    echo 'if [ -d "$TOOLS_HOME/bin" ]; then'
    echo '    case ":$PATH:" in'
    echo '        *":$TOOLS_HOME/bin:"*) ;;'
    echo '        *) PATH="$TOOLS_HOME/bin:$PATH"; export PATH ;;'
    echo '    esac'
    echo 'fi'
    echo "$END_MARK"
} >> "$RC"

# --------------------------------------------------------------------------
echo "installed:$linked"
echo "  repo:   $ROOT"
echo "  python: $VENV/bin/python3"
echo "  PATH block written to: $RC"
if [ -n "$missing" ]; then
    echo ""
    echo "  still missing:$missing"
    echo "  no network? install by hand, then re-run:"
    echo "      $VENV/bin/python3 -m pip install$missing"
fi
echo ""
echo "run:  source $RC"
